trigger:
  branches:
    include:
      - main

pool:
  name: LocalAgentPool  # ✅ Your self-hosted agent pool

jobs:
- job: BuildAndPush
  displayName: 'Build and Push Docker Image'
  steps:
    - checkout: self
      clean: true
      fetchTags: false

    - task: Maven@4
      displayName: 'Maven Build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        options: '-DskipTests'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: 'acr-connection'       # ✅ Docker Registry service connection
        repository: 'springboot-app'              # ✅ Image name only
        command: build
        Dockerfile: 'Dockerfile'
        buildContext: '.'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: 'acr-connection'
        repository: 'springboot-app'
        command: push
        tags: |
          $(Build.BuildId)
          latest

    - task: CopyFiles@2
      displayName: 'Copy Deployment YAML'
      inputs:
        Contents: 'updated-acr.yaml
